/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.nx.gradle.project-graph") version("0.1.0")
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

allprojects {
    apply {
        plugin("dev.nx.gradle.project-graph")
    }
}